# Project Information
site_name: MDnotes

# Copyright
copyright: Copyright &copy; 2021 Jasper Ho

# Configuration
theme:
  name: material
  custom_dir: overrides
  icon:
    logo: material/pill
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

plugins:
  - search:
      prebuild_index: true
  - minify:
      minify_html: true
  - git-revision-date-localized

markdown_extensions:
  - smarty
  - sane_lists
  - attr_list
  - admonition
  - pymdownx.superfences
  - pymdownx.details
  - footnotes

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/jasperchho
