theme:
    name: material
    features:
      - search.suggest
      - search.highlight
site_name: mdNotes
plugins:
    - search:
        lang: en
markdown_extensions:
    - smarty
    - sane_lists
    - attr_list